/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunRouteImport } from './routes/run'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as ShowcaseQuestionsRouteImport } from './routes/showcase.questions'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TestsIdRunRouteImport } from './routes/tests.$id.run'
import { Route as ResultSelfVariantRouteImport } from './routes/result.self.$variant'

const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseQuestionsRoute = ShowcaseQuestionsRouteImport.update({
  id: '/showcase/questions',
  path: '/showcase/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const TestsIdRunRoute = TestsIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => TestsIdRoute,
} as any)
const ResultSelfVariantRoute = ResultSelfVariantRouteImport.update({
  id: '/result/self/$variant',
  path: '/result/self/$variant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/showcase/questions': typeof ShowcaseQuestionsRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/result/self/$variant': typeof ResultSelfVariantRoute
  '/tests/$id/run': typeof TestsIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/showcase/questions': typeof ShowcaseQuestionsRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/result/self/$variant': typeof ResultSelfVariantRoute
  '/tests/$id/run': typeof TestsIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/run': typeof RunRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/showcase/questions': typeof ShowcaseQuestionsRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/result/self/$variant': typeof ResultSelfVariantRoute
  '/tests/$id/run': typeof TestsIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/run'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/showcase/questions'
    | '/tests/$id'
    | '/result/self/$variant'
    | '/tests/$id/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/run'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/showcase/questions'
    | '/tests/$id'
    | '/result/self/$variant'
    | '/tests/$id/run'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/run'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/showcase/questions'
    | '/tests/$id'
    | '/result/self/$variant'
    | '/tests/$id/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AnalyzingRoute: typeof AnalyzingRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  RunRoute: typeof RunRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  ShowcaseQuestionsRoute: typeof ShowcaseQuestionsRoute
  TestsIdRoute: typeof TestsIdRouteWithChildren
  ResultSelfVariantRoute: typeof ResultSelfVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/tests/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/questions': {
      id: '/showcase/questions'
      path: '/showcase/questions'
      fullPath: '/showcase/questions'
      preLoaderRoute: typeof ShowcaseQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/tests/$id/run': {
      id: '/tests/$id/run'
      path: '/run'
      fullPath: '/tests/$id/run'
      preLoaderRoute: typeof TestsIdRunRouteImport
      parentRoute: typeof TestsIdRoute
    }
    '/result/self/$variant': {
      id: '/result/self/$variant'
      path: '/result/self/$variant'
      fullPath: '/result/self/$variant'
      preLoaderRoute: typeof ResultSelfVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TestsIdRouteChildren {
  TestsIdRunRoute: typeof TestsIdRunRoute
}

const TestsIdRouteChildren: TestsIdRouteChildren = {
  TestsIdRunRoute: TestsIdRunRoute,
}

const TestsIdRouteWithChildren =
  TestsIdRoute._addFileChildren(TestsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AnalyzingRoute: AnalyzingRoute,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  RunRoute: RunRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  ShowcaseQuestionsRoute: ShowcaseQuestionsRoute,
  TestsIdRoute: TestsIdRouteWithChildren,
  ResultSelfVariantRoute: ResultSelfVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
