/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as RosStartRouteImport } from './routes/ros.start'
import { Route as ResultAttemptIdRouteImport } from './routes/result.$attemptId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminCodesRouteImport } from './routes/admin/codes'
import { Route as AdminAnalystsRouteImport } from './routes/admin/analysts'
import { Route as TestsIdRunRouteImport } from './routes/tests.$id.run'
import { Route as RosInviteCodeRouteImport } from './routes/ros.invite.$code'
import { Route as ResultRosIdRouteImport } from './routes/result.ros.$id'
import { Route as ResultMateIdRouteImport } from './routes/result.mate.$id'
import { Route as MateInviteCodeRouteImport } from './routes/mate.invite.$code'
import { Route as ResultRosCoupleCodeRouteImport } from './routes/result.ros.couple.$code'
import { Route as ResultMateCoupleCodeRouteImport } from './routes/result.mate.couple.$code'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RosStartRoute = RosStartRouteImport.update({
  id: '/ros/start',
  path: '/ros/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultAttemptIdRoute = ResultAttemptIdRouteImport.update({
  id: '/result/$attemptId',
  path: '/result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCodesRoute = AdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalystsRoute = AdminAnalystsRouteImport.update({
  id: '/analysts',
  path: '/analysts',
  getParentRoute: () => AdminRoute,
} as any)
const TestsIdRunRoute = TestsIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => TestsIdRoute,
} as any)
const RosInviteCodeRoute = RosInviteCodeRouteImport.update({
  id: '/ros/invite/$code',
  path: '/ros/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRosIdRoute = ResultRosIdRouteImport.update({
  id: '/result/ros/$id',
  path: '/result/ros/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultMateIdRoute = ResultMateIdRouteImport.update({
  id: '/result/mate/$id',
  path: '/result/mate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MateInviteCodeRoute = MateInviteCodeRouteImport.update({
  id: '/mate/invite/$code',
  path: '/mate/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRosCoupleCodeRoute = ResultRosCoupleCodeRouteImport.update({
  id: '/result/ros/couple/$code',
  path: '/result/ros/couple/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultMateCoupleCodeRoute = ResultMateCoupleCodeRouteImport.update({
  id: '/result/mate/couple/$code',
  path: '/result/mate/couple/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/admin/analysts': typeof AdminAnalystsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/ros/start': typeof RosStartRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/mate/invite/$code': typeof MateInviteCodeRoute
  '/result/mate/$id': typeof ResultMateIdRoute
  '/result/ros/$id': typeof ResultRosIdRoute
  '/ros/invite/$code': typeof RosInviteCodeRoute
  '/tests/$id/run': typeof TestsIdRunRoute
  '/result/mate/couple/$code': typeof ResultMateCoupleCodeRoute
  '/result/ros/couple/$code': typeof ResultRosCoupleCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/admin/analysts': typeof AdminAnalystsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/ros/start': typeof RosStartRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/mate/invite/$code': typeof MateInviteCodeRoute
  '/result/mate/$id': typeof ResultMateIdRoute
  '/result/ros/$id': typeof ResultRosIdRoute
  '/ros/invite/$code': typeof RosInviteCodeRoute
  '/tests/$id/run': typeof TestsIdRunRoute
  '/result/mate/couple/$code': typeof ResultMateCoupleCodeRoute
  '/result/ros/couple/$code': typeof ResultRosCoupleCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRouteWithChildren
  '/analyzing': typeof AnalyzingRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/admin/analysts': typeof AdminAnalystsRoute
  '/admin/codes': typeof AdminCodesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/result/$attemptId': typeof ResultAttemptIdRoute
  '/ros/start': typeof RosStartRoute
  '/tests/$id': typeof TestsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/mate/invite/$code': typeof MateInviteCodeRoute
  '/result/mate/$id': typeof ResultMateIdRoute
  '/result/ros/$id': typeof ResultRosIdRoute
  '/ros/invite/$code': typeof RosInviteCodeRoute
  '/tests/$id/run': typeof TestsIdRunRoute
  '/result/mate/couple/$code': typeof ResultMateCoupleCodeRoute
  '/result/ros/couple/$code': typeof ResultRosCoupleCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/admin/analysts'
    | '/admin/codes'
    | '/admin/users'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/ros/start'
    | '/tests/$id'
    | '/admin/'
    | '/mate/invite/$code'
    | '/result/mate/$id'
    | '/result/ros/$id'
    | '/ros/invite/$code'
    | '/tests/$id/run'
    | '/result/mate/couple/$code'
    | '/result/ros/couple/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/admin/analysts'
    | '/admin/codes'
    | '/admin/users'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/ros/start'
    | '/tests/$id'
    | '/admin'
    | '/mate/invite/$code'
    | '/result/mate/$id'
    | '/result/ros/$id'
    | '/ros/invite/$code'
    | '/tests/$id/run'
    | '/result/mate/couple/$code'
    | '/result/ros/couple/$code'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/admin'
    | '/analyzing'
    | '/auth'
    | '/chat'
    | '/history'
    | '/admin/analysts'
    | '/admin/codes'
    | '/admin/users'
    | '/auth/callback'
    | '/result/$attemptId'
    | '/ros/start'
    | '/tests/$id'
    | '/admin/'
    | '/mate/invite/$code'
    | '/result/mate/$id'
    | '/result/ros/$id'
    | '/ros/invite/$code'
    | '/tests/$id/run'
    | '/result/mate/couple/$code'
    | '/result/ros/couple/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyzingRoute: typeof AnalyzingRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  ResultAttemptIdRoute: typeof ResultAttemptIdRoute
  RosStartRoute: typeof RosStartRoute
  TestsIdRoute: typeof TestsIdRouteWithChildren
  MateInviteCodeRoute: typeof MateInviteCodeRoute
  ResultMateIdRoute: typeof ResultMateIdRoute
  ResultRosIdRoute: typeof ResultRosIdRoute
  RosInviteCodeRoute: typeof RosInviteCodeRoute
  ResultMateCoupleCodeRoute: typeof ResultMateCoupleCodeRoute
  ResultRosCoupleCodeRoute: typeof ResultRosCoupleCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/tests/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ros/start': {
      id: '/ros/start'
      path: '/ros/start'
      fullPath: '/ros/start'
      preLoaderRoute: typeof RosStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$attemptId': {
      id: '/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof ResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/codes': {
      id: '/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AdminCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analysts': {
      id: '/admin/analysts'
      path: '/analysts'
      fullPath: '/admin/analysts'
      preLoaderRoute: typeof AdminAnalystsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tests/$id/run': {
      id: '/tests/$id/run'
      path: '/run'
      fullPath: '/tests/$id/run'
      preLoaderRoute: typeof TestsIdRunRouteImport
      parentRoute: typeof TestsIdRoute
    }
    '/ros/invite/$code': {
      id: '/ros/invite/$code'
      path: '/ros/invite/$code'
      fullPath: '/ros/invite/$code'
      preLoaderRoute: typeof RosInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/ros/$id': {
      id: '/result/ros/$id'
      path: '/result/ros/$id'
      fullPath: '/result/ros/$id'
      preLoaderRoute: typeof ResultRosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/mate/$id': {
      id: '/result/mate/$id'
      path: '/result/mate/$id'
      fullPath: '/result/mate/$id'
      preLoaderRoute: typeof ResultMateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mate/invite/$code': {
      id: '/mate/invite/$code'
      path: '/mate/invite/$code'
      fullPath: '/mate/invite/$code'
      preLoaderRoute: typeof MateInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/ros/couple/$code': {
      id: '/result/ros/couple/$code'
      path: '/result/ros/couple/$code'
      fullPath: '/result/ros/couple/$code'
      preLoaderRoute: typeof ResultRosCoupleCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/mate/couple/$code': {
      id: '/result/mate/couple/$code'
      path: '/result/mate/couple/$code'
      fullPath: '/result/mate/couple/$code'
      preLoaderRoute: typeof ResultMateCoupleCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalystsRoute: typeof AdminAnalystsRoute
  AdminCodesRoute: typeof AdminCodesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalystsRoute: AdminAnalystsRoute,
  AdminCodesRoute: AdminCodesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TestsIdRouteChildren {
  TestsIdRunRoute: typeof TestsIdRunRoute
}

const TestsIdRouteChildren: TestsIdRouteChildren = {
  TestsIdRunRoute: TestsIdRunRoute,
}

const TestsIdRouteWithChildren =
  TestsIdRoute._addFileChildren(TestsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyzingRoute: AnalyzingRoute,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  ResultAttemptIdRoute: ResultAttemptIdRoute,
  RosStartRoute: RosStartRoute,
  TestsIdRoute: TestsIdRouteWithChildren,
  MateInviteCodeRoute: MateInviteCodeRoute,
  ResultMateIdRoute: ResultMateIdRoute,
  ResultRosIdRoute: ResultRosIdRoute,
  RosInviteCodeRoute: RosInviteCodeRoute,
  ResultMateCoupleCodeRoute: ResultMateCoupleCodeRoute,
  ResultRosCoupleCodeRoute: ResultRosCoupleCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
