#!/usr/bin/env node
/**
 * Switch LoveCompass from EU Supabase (wjfpglsygkbpubanylug) to SG (busyjidkgfakqglldyye).
 *
 * Usage:
 *   SG_DB_PASSWORD='your-lovecompass-sg-db-password' node scripts/activate_supabase_sg.mjs
 *
 * Password: Supabase Dashboard → lovecompass-sg → Settings → Database → Reset database password
 * (Use the same password as EU if you want one password for both during transition.)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OLD_REF = "wjfpglsygkbpubanylug";
const NEW_REF = "busyjidkgfakqglldyye";
const NEW_URL = `https://${NEW_REF}.supabase.co`;
const NEW_ANON =
  process.env.SG_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1c3lqaWRrZ2Zha3FnbGxkeXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4MTMyODksImV4cCI6MjA5NTM4OTI4OX0.IDXwoThWojq4nebuipwfqf6VFpdR6m_7GMf6G2LSAXs";
const NEW_PUBLISHABLE =
  process.env.SG_PUBLISHABLE_KEY || "sb_publishable_J5dSTCN5sbTAnbUczTVciA_iOPUmqkR";

const password = process.env.SG_DB_PASSWORD || process.env.SUPABASE_DB_PASSWORD;
if (!password) {
  console.error(
    "Missing SG_DB_PASSWORD. Reset lovecompass-sg database password in Supabase Dashboard, then re-run:\n" +
      "  SG_DB_PASSWORD='...' node scripts/activate_supabase_sg.mjs",
  );
  process.exit(1);
}

const enc = encodeURIComponent(password);
const DATABASE_URL = `postgresql://postgres.${NEW_REF}:${enc}@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true`;
const DIRECT_URL = `postgresql://postgres:${enc}@db.${NEW_REF}.supabase.co:5432/postgres`;
const TARGET_DIRECT_URL = `postgresql://postgres.${NEW_REF}:${enc}@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres`;

function patchEnvFile(path, updates, header) {
  if (!existsSync(path)) return;
  const lines = readFileSync(path, "utf8").split("\n");
  const keys = new Set(Object.keys(updates));
  const out = [];
  const seen = new Set();
  if (header) out.push(header);
  for (const line of lines) {
    const m = line.match(/^([A-Z0-9_]+)=/);
    if (m && keys.has(m[1])) {
      out.push(`${m[1]}=${updates[m[1]]}`);
      seen.add(m[1]);
    } else if (!header || !line.startsWith("# Auto-generated by scripts/activate_supabase_sg")) {
      out.push(line);
    }
  }
  for (const [k, v] of Object.entries(updates)) {
    if (!seen.has(k)) out.push(`${k}=${v}`);
  }
  writeFileSync(path, out.filter((l, i, a) => !(i === a.length - 1 && l === "")).join("\n") + "\n");
  console.log("updated", path);
}

patchEnvFile(join(root, "backend/.env"), {
  DATABASE_URL,
  DIRECT_URL,
  TARGET_DIRECT_URL,
  SUPABASE_URL: NEW_URL,
  SUPABASE_PROJECT_ID: NEW_REF,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: NEW_ANON,
  SUPABASE_PUBLISHABLE_KEY: NEW_PUBLISHABLE,
});

patchEnvFile(join(root, "frontend/.env.preview"), {
  NEXT_PUBLIC_SUPABASE_URL: NEW_URL,
  VITE_SUPABASE_URL: NEW_URL,
  VITE_SUPABASE_PROJECT_ID: NEW_REF,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: NEW_ANON,
  VITE_SUPABASE_ANON_KEY: NEW_ANON,
  VITE_SUPABASE_PUBLISHABLE_KEY: NEW_PUBLISHABLE,
});

const vercelEnvPath = join(root, "docs/vercel-env-sg.txt");
writeFileSync(
  vercelEnvPath,
  `# Paste into Vercel → lovecompass-api-backend (Production)
DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DIRECT_URL}
SUPABASE_URL=${NEW_URL}
SUPABASE_PROJECT_ID=${NEW_REF}

# Paste into Vercel → lovecompass-web (Production)
NEXT_PUBLIC_SUPABASE_URL=${NEW_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEW_ANON}
VITE_SUPABASE_URL=${NEW_URL}
VITE_SUPABASE_ANON_KEY=${NEW_ANON}
VITE_SUPABASE_PUBLISHABLE_KEY=${NEW_PUBLISHABLE}
VITE_SUPABASE_PROJECT_ID=${NEW_REF}

# Supabase Dashboard → lovecompass-sg → Authentication → URL Configuration
# Site URL: https://lovecompass-web.vercel.app
# Redirect URLs: https://lovecompass-web.vercel.app/auth**
`,
);
console.log("wrote", vercelEnvPath);
console.log("\nNext: Redeploy Vercel backend + frontend, then verify /health?db=1");
